### ISSUE TITLE
Including ackerman_msgs to project fails

### ISSUE THREAD

**Issue by doenerfriend** [ros-drivers/ackermann_msgs#10]
Hi :)

I am trying to use ackermann_msgs in a project, but the include can't find the cmake project.
I am using ROS-Melodic. Did I forget to do something?

My cmake file is is included.
[CMakeLists.txt](https://github.com/ros-drivers/ackermann_msgs/files/3865753/CMakeLists.txt)

This is the error message:
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "ackermann_msgs"
  with any of the following names:

    ackermann_msgsConfig.cmake
    ackermann_msgs-config.cmake

  Add the installation prefix of "ackermann_msgs" to CMAKE_PREFIX_PATH or set
  "ackermann_msgs_DIR" to a directory containing one of the above files.  If
  "ackermann_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  road-follow-planner/CMakeLists.txt:10 (find_package)

**Comment by doenerfriend** [comment]
Sorry I forgot to install the package with apt-get. I thought it was in the basic ros distribution included.

**Comment by RonakMatai** [comment]
Hi, i'm receiving the same error, could you help me out with which package to install with apt-get?

**Comment by laercio-barbosa** [comment]
Hi

The same here. Using humble under Windows 10. How to install this package on Windows?

@vincentrou, maybe you have an idea on how to do it.

**Comment by vincentrou** [comment]
Sorry, I do not use Windows.
On my side on linux, I do `sudo apt install ros-humble-ackermann-msgs`.

**Comment by laercio-barbosa** [comment]
Thank you anyway, @vincentrou 

I will just mention here how I solve it for someone else that reach this thread.

Considereing:
My ROS2 folder: `c:\dev\ros2_humble`
My workspace folder: `c:\git\my_proj\ros2_ws`
My build folder: `c:\dev\build_pkg`
My OS: `Windows 10`
My ROS2 flavor: `Humble`


### Install ackerman package manually on Windows

**1. Clone the ros2 branch into src folder in my workspace:**

```bash
cd c:\git\my_proj\ros2_ws\src
git clone -b ros2 https://github.com/ros-drivers/ackermann_msgs.git
```

**2. Create a temparay folder to store the built files:**

```bash
md c:\dev\build_pkg
```


**3. Build ackermann_msgs package:**
> To build packages on Windows you need to be in a Visual Studio environment, see [Building the ROS 2 Code](https://docs.ros.org/en/humble/Installation/Alternatives/Windows-Development-Setup.html#windows-dev-build-ros2) for more details. So, a Visual Studio Command Prompt (“x64 Native Tools Command Prompt for VS 2019”) running as Administrator.

```bash
cd c:\git\my_proj\ros2_ws
colcon build --install-base "c:\dev\build_pkg" --packages-select ackermann_msgs
```

**4. Copy built files to ROS2 folder:**

```bash
xcopy c:\dev\build_pkg\ackermann_msgs c:\dev\ros2_humble /E /H
```


Now you can use ackermann package in any new project!
