### ISSUE TITLE
left / right wheel angles, etc

### ISSUE THREAD

**Issue by AllanSchergerGitHub** [ros-drivers/ackermann_msgs#13]
Is there existing code that will convert these messages into the angles; speeds; etc for the left and right wheels? and possibly all 4 wheels if all 4 wheels are controlled with motors? These messages provide one steering angle (and speed, etc) for the rover (like a tricycle per the documentation); but we need to have a way to convert this angle (and speed, etc) into the angles for the individual wheels. Thanks

**Comment by vincentrou** [comment]
Some examples :
* https://github.com/Romea/romea_controllers/tree/master/ackermann_controller
* https://github.com/easymov/ackermann_controller
* https://github.com/ros-controls/ros_controllers/tree/noetic-devel/ackermann_steering_controller

Hope it helps
