### ISSUE TITLE
 ‘ackermann_msgs’ was not declared in this scope

### ISSUE THREAD

**Issue by leaves369** [ros-drivers/ackermann_msgs#18]
i have install  ‘ackermann_msgs’ by the command, and use  ‘ackermann_msgs to write a publisher, when done,  **it occurs <error: ‘ackermann_msgs’ was not declared in this scope>**  cmakelist has already added find_package(ackermann_msgs REQUIRED) ament_target_dependencies(talker rclcpp std_msgs ackermann_msgs) same with the package.xml

**Comment by alesof** [comment]
Have you included the message? Your cpp should contain something like:

```
#include "ackermann_msgs/msg/ackermann_drive_stamped.hpp
[...]
ackermann_msgs::msg::AckermannDriveStamped test;
```
