### ISSUE TITLE
find a better home for this package

### ISSUE THREAD

**Issue by jack-oquin** [ros-drivers/ackermann_msgs#2]
Other ROS packages depend on it. It should not remain in my personal github account.

**Comment by jack-oquin** [comment]
Moved it to ros-drivers.

**Comment by jack-oquin** [comment]
@wunderkammer-laboratory: should we make a 1.0.0 release from this?

**Comment by jim-rothrock** [comment]
Yes.

**Comment by jack-oquin** [comment]
You want to do that release? That will prove we've gotten all the permissions and links right.

(I can do it if you are busy with other things.)

**Comment by jim-rothrock** [comment]
I'll do the release.

**Comment by jim-rothrock** [comment]
When I run the following:

    bloom-release ackermann_msgs --track indigo --rosdistro indigo

I get a series of error messages ending with:

    ValueError: No JSON object could be decoded

I've googled for an explanation of the error, but haven't found anything. Do you know why this error might be occurring?

**Comment by jack-oquin** [comment]
The source repo looks ready and has the right tag. I was able to run it here, OK. It wanted to update the "actions". I told it not to push to the release repository so we can figure out what the problem is.

Aha! The bloom track has this out-of-date URI for all three tracks:
```
vcs_uri: https://github.com/jack-oquin/ackermann_msgs.git
```
I think it worked for me because github forwards the old URL to the new one.

You should try again, adding the ``-e`` option and deleting that URI when it comes up:
```
bloom-release ackermann_msgs -t indigo -r indigo -e
```

**Comment by jim-rothrock** [comment]
I ran

    bloom-release ackermann_msgs -t indigo -r indigo -e

It printed the same "No JSON object could be decoded" message as before.

**Comment by jack-oquin** [comment]
OK. Please try it again. 

The ``release_repo_url`` value was also broken. I updated all three tracks by hand.

**Comment by jim-rothrock** [comment]
Still no luck. Here is the traceback:

    Traceback (most recent call last):
      File "/usr/bin/bloom-release", line 9, in <module>
        load_entry_point('bloom==0.5.20', 'console_scripts', 'bloom-release')()
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1314, in main
        args.override_release_repository_push_url)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 1166, in perform_release
        release_repo = get_release_repo(repository, distro, override_release_repository_url)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 358, in get_release_repo
        url = get_repo_uri(repository, distro)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 306, in get_repo_uri
    distribution_file = get_distribution_file(distro)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 255, in get_distribution_file
        files = rosdistro.get_distribution_files(get_index(), distro)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 216, in get_index
        _rosdistro_index = rosdistro.get_index(get_index_url())
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 186, in get_index_url
    gh = get_github_interface(quiet=True)
      File "/usr/lib/python2.7/dist-packages/bloom/commands/release.py", line 657, in get_github_interface
        config = json.loads(f.read())
      File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by jack-oquin** [comment]
Looking at the traceback, it's trying to read your ``~/.config/bloom`` and that is not working.

I've had oauth problems from time to time. Usually, I end up deleting that file and things start working again. Have you tried any other bloom releases lately on that machine? 

Is your home directory shared between multiple systems? I had trouble with that in the UTexas robotics lab, although I think the error message was different.

If we can't figure this out soon, let's inquire on the ros-release mailing list.

**Comment by jim-rothrock** [comment]
Deleting ~/.config/bloom (which was empty) fixed the problem. Now when I run

    bloom-release ackermann_msgs -t indigo -r indigo

the following message is displayed:

    Your track's 'actions' configuration is not the same as the default.
    Unless you have manually modified your 'actions' (the commands which get run for a release), 
    you should update to the new default.
    Should it be updated to the default setting?
    Continue [Y/n]?

Should I answer Y, or n?

**Comment by jack-oquin** [comment]
Answer Y.

It's been a long time since that package was released, and bloom wants to update the tracks file.

**Comment by jim-rothrock** [comment]
Okay, I answered Y. After entering my GitHub user name and password, I got this:

    To https://github.com/ros-drivers/ackermann_msgs.git
     ! [rejected]        master -> master (fetch first)
    error: failed to push some refs to 'https://github.com/ros-drivers/ackermann_msgs.git'
    hint: Updates were rejected because the remote contains work that you do
    hint: not have locally. This is usually caused by another repository pushing
    hint: to the same ref. You may want to first integrate the remote changes
    hint: (e.g., 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    Cannot push to remote release repository.

I then tried a few variations of "git pull" (e.g. "git pull", "git pull origin master"), but I always get the response "Already up-to-date." I've tried to find a solution, but everything I've found on the web is basically "git pull will fix it." I'm sorry I'm having so much trouble getting this release to work.

**Comment by jack-oquin** [comment]
Hmm. Looks like I screwed up the release repo URL in 9176cfa19deace664584018a61301442641135b1, when I tried editing the tracks.yaml file by hand.

**Comment by jack-oquin** [comment]
I hope I've gotten it right this time. I apologize for my many errors.

Thanks for your patience! Please try it again.

**Comment by jim-rothrock** [comment]
Now I get this error after I enter my user name and password (a personal access token):

    remote: Permission to ros-drivers-gbp/ackermann_msgs-release.git denied to jim-rothrock.
    fatal: unable to access 'https://github.com/ros-drivers-gbp/ackermann_msgs-release.git/': The requested URL returned error: 403
    Cannot push to remote release repository.

**Comment by jack-oquin** [comment]
I forgot to link the Ackermann Maintainers team to the release repository. You should have access now.

**Comment by jim-rothrock** [comment]
I released ackermann_msgs for ROS Hydro, Indigo, and Jade.

**Comment by jack-oquin** [comment]
Thanks for your admirable persistence.

I didn't think they were accepting new Hydro releases any more, but do not expect any harm from it.
