### ISSUE TITLE
Integration of four_wheel_steering_msgs

### ISSUE THREAD

**Issue by vincentrou** [ros-drivers/ackermann_msgs#4]
I would like to integrate the [four_wheel_steering_msgs](four_wheel_steering_msgs) in the official ROS repo for kinetic.

Actually a [four_wheel_steering_controller](http://wiki.ros.org/four_wheel_steering_controller?distro=indigo) is using it. I wish to integrate it in the `ros_controllers` repo. https://github.com/ros-controls/ros_controllers/issues/55#issuecomment-293845743

What is the best thing to do for the `four_wheel_steering_msgs` ?
-  create a new repo in ros-drivers for `four_wheel_steering_msgs`
-  create a new repo named `vehicle_msgs` where we can put the two package  `ackermann_msgs` and `four_wheel_steering_msgs`

**Comment by jack-oquin** [comment]
I favor using separate repositories, so they can be maintained and released independently.

**Comment by vincentrou** [comment]
@jack-oquin  I am fine with independent git repo.

Is it possible to move the [four_wheel_steering_msgs](https://github.com/Romea/romea_controllers/tree/master/four_wheel_steering_msgs) package from our unofficial ROS organization in a new ros-drivers organization repo for a kinetic release ? (since it is an extension of the `ackermann_msgs`)

Otherwise I can ask to create the `four_wheel_steering_msgs` repo in the ros-controls organization. But it makes more sense to me to put `four_wheel_steering_msgs` and `ackermann_msgs` in the same organization.

**Comment by jack-oquin** [comment]
Sure, no problem. Do you want me to create a ``ros-drivers/four_wheel_steering_msgs`` repo for it?

As an aside, having just looked at the messages, I'd recommend adding ``jerk`` to ``speed`` and ``acceleration``. It is helpful for smooth control, and can be ignored (left zero) by controllers that don't care about it. Some people would even argue that the fourth derivative, ``snap``, should be included, but we didn't do that for ``ackermann_msgs``.

**Comment by vincentrou** [comment]
Yes, it would be great if you create a `ros-drivers/four_wheel_steering_msgs` repo.

We remove the jerk because it does not seem useful for us but I can add it back for the kinetic release on these new repo.

**Comment by jack-oquin** [comment]
That would be my recommendation. Just adding the field and letting it default to zero should not break and existing code.

**Comment by jack-oquin** [comment]
I created an empty repository and added you to the ackermann maintainers team with access to both ackermann_msgs and the four_wheel_steering_msgs.

**Comment by jack-oquin** [comment]
I could have missed something administrative. Let me know if there are problems.

**Comment by jack-oquin** [comment]
I added you first as a collaborator, then remembered to add you to the ackermann maintainers team. You'll probably get two notifications, one each. You really only need to join the team.

**Comment by vincentrou** [comment]
Everything seems to be fine.
I have push the package in the repo.
Feel free to create issue in the four_wheel_steering_msgs repo if you have question.

**Comment by jack-oquin** [comment]
Looks like it's working now.

Would you like to take over maintaining ``ackermann_msgs``, too? It's not much work, but I'm not using it for any of my current activities.

**Comment by vincentrou** [comment]
Yes I can also maintain `ackermann_msgs` since it is very similar to the `four_wheel_steering_msgs`

**Comment by jack-oquin** [comment]
That's great, thanks!
