### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by aarontan94** [ros-drivers/ackermann_msgs#6]
Hello,

This isn't much of an issue, only a question.

I am new to ROS.

If i want to use an Arduino to control some steering servo motors, and I'd like to control this using ROS for an ackermann steered vehicle, what do I need?

How do i combine [this](http://wiki.ros.org/rosserial_arduino/Tutorials/Servo%20Controller) with the ackermann_msgs?

Thanks,
Aaron

**Comment by vincentrou** [comment]
You found the right place to post your question.
https://answers.ros.org/question/295065/ackermann-steering-and-arduino-servo-control/
